# docker build -f Dockerfile.dm8 . -t dm8_server

FROM dm8_single:v8.1.2.128_ent_x86_64_ctm_pack4

WORKDIR /

RUN apt update
RUN apt install unixodbc unixodbc-dev -y
RUN echo -e "[DM8 ODBC DRIVER]\nDescription = ODBC DRIVER FOR DM8\nDriver = /opt/dmdbms/bin/libdodbc.so" > /etc/odbcinst.ini
RUN echo -e "[dm]\nDescription = DM ODBC DSN\nDriver = DM8 ODBC DRIVER\nSERVER = localhost\nUID = SYSDBA\nPWD = SYSDBA001\nTCP_PORT = 5236" > /etc/odbc.ini

CMD /opt/startup.sh