FROM python:3.11-alpine

ENV PYTHONUNBUFFERED=1

RUN mkdir /app

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install pyodbc django pandas numpy openpyxl

COPY ../src /app

RUN python manage.py migrate

EXPOSE 8000

CMD python manage.py runserver 0.0.0.0:8000